name: Testing & Deploying Action
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, closed, edited]
  workflow_dispatch:

jobs:
  Build:
    runs-on: self-hosted
    steps:
      - name: Set up repository
        uses: actions/checkout@v4
      - name: Configure JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '22'
          cache: maven
      - name: Check directory
        run: pwd && ls
      - name: Check dependencies
        run: echo $PATH
      - name: Build JAR
        run: ./mvnw clean package --file pom.xml -DskipTests
  Test:
    runs-on: self-hosted
    steps:
      - run: ./mvnw test
    continue-on-error: false
    needs: Build
#docker build -t geo .
#docker container run -d -p 8080:8080 -e USER_PASSWORD=88428388-262c-4e60-bbf5-5b43ca8f7b98 geo
  Build-Docker-Image:
    runs-on: self-hosted
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: vova/geo:latest
    continue-on-error: false
    needs: Test