name: Testing & Deploying Action
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, closed, edited]
  workflow_dispatch:

jobs:
  Build:
    runs-on: self-hosted
    steps:
      - name: Set up repository
        uses: actions/checkout@v4
#      - name: Configure JDK
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'temurin'
#          java-version: '22'
#          cache: maven
      - name: Build JAR
        run: ./mvnw clean package --file pom.xml -DskipTests

  Test:
    runs-on: self-hosted
    steps:
      - run: ./mvnw test
    continue-on-error: false
    needs: Build

  Build-Docker-Image:
    runs-on: self-hosted
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: volodpol/github-images
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
    continue-on-error: false
    needs: Test