name: Testing & Deploying Action
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, closed, edited]
jobs:
  Build:
    runs-on: self-hosted
    steps:
      - name: Set up repository
        uses: actions/checkout@v4
      - name: Configure JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '22.0.2'
          cache: maven
      - name: Check directory
        run: pwd && ls
      - name: Check dependencies
        run: echo $PATH
      - name: Build JAR
        run: ./mvnw clean package --file pom.xml -DskipTests

  Test:
    runs-on: self-hosted
    steps:
      - run: ./mvnw test
    continue-on-error: false
    needs: Build
